const DISCORD_PERMISSIONS = {
  MODERATE_MEMBERS: 'ModerateMembers',
  MANAGE_MESSAGES: 'ManageMessages',
  ADMINISTRATOR: 'Administrator',
  KICK_MEMBERS: 'KickMembers',
  BAN_MEMBERS: 'BanMembers'
};

const USER_ROLES = {
  ADMIN: 'ADMIN',
  USER: 'USER'
};

// Discord Permission Flags (BigInt values as strings for JSON compatibility)
const PERMISSION_FLAGS = {
  CREATE_INSTANT_INVITE: '1',
  KICK_MEMBERS: '2',
  BAN_MEMBERS: '4',
  ADMINISTRATOR: '8',
  MANAGE_CHANNELS: '16',
  MANAGE_GUILD: '32',
  ADD_REACTIONS: '64',
  VIEW_AUDIT_LOG: '128',
  PRIORITY_SPEAKER: '256',
  STREAM: '512',
  VIEW_CHANNEL: '1024',
  SEND_MESSAGES: '2048',
  SEND_TTS_MESSAGES: '4096',
  MANAGE_MESSAGES: '8192',
  EMBED_LINKS: '16384',
  ATTACH_FILES: '32768',
  READ_MESSAGE_HISTORY: '65536',
  MENTION_EVERYONE: '131072',
  USE_EXTERNAL_EMOJIS: '262144',
  VIEW_GUILD_INSIGHTS: '524288',
  CONNECT: '1048576',
  SPEAK: '2097152',
  MUTE_MEMBERS: '4194304',
  DEAFEN_MEMBERS: '8388608',
  MOVE_MEMBERS: '16777216',
  USE_VAD: '33554432',
  CHANGE_NICKNAME: '67108864',
  MANAGE_NICKNAMES: '134217728',
  MANAGE_ROLES: '268435456',
  MANAGE_WEBHOOKS: '536870912',
  MANAGE_EMOJIS_AND_STICKERS: '1073741824',
  USE_APPLICATION_COMMANDS: '2147483648',
  REQUEST_TO_SPEAK: '4294967296',
  MANAGE_EVENTS: '8589934592',
  MANAGE_THREADS: '17179869184',
  CREATE_PUBLIC_THREADS: '34359738368',
  CREATE_PRIVATE_THREADS: '68719476736',
  USE_EXTERNAL_STICKERS: '137438953472',
  SEND_MESSAGES_IN_THREADS: '274877906944',
  USE_EMBEDDED_ACTIVITIES: '549755813888',
  MODERATE_MEMBERS: '1099511627776',
  VIEW_CREATOR_MONETIZATION_ANALYTICS: '2199023255552',
  USE_SOUNDBOARD: '4398046511104',
  SEND_VOICE_MESSAGES: '70368744177664'
};

// Human-readable permission names for UI
const PERMISSION_NAMES = {
  CREATE_INSTANT_INVITE: 'Create Invite',
  KICK_MEMBERS: 'Kick Members',
  BAN_MEMBERS: 'Ban Members',
  ADMINISTRATOR: 'Administrator',
  MANAGE_CHANNELS: 'Manage Channels',
  MANAGE_GUILD: 'Manage Server',
  ADD_REACTIONS: 'Add Reactions',
  VIEW_AUDIT_LOG: 'View Audit Log',
  PRIORITY_SPEAKER: 'Priority Speaker',
  STREAM: 'Video',
  VIEW_CHANNEL: 'View Channel',
  SEND_MESSAGES: 'Send Messages',
  SEND_TTS_MESSAGES: 'Send TTS Messages',
  MANAGE_MESSAGES: 'Manage Messages',
  EMBED_LINKS: 'Embed Links',
  ATTACH_FILES: 'Attach Files',
  READ_MESSAGE_HISTORY: 'Read Message History',
  MENTION_EVERYONE: 'Mention Everyone',
  USE_EXTERNAL_EMOJIS: 'Use External Emojis',
  VIEW_GUILD_INSIGHTS: 'View Server Insights',
  CONNECT: 'Connect',
  SPEAK: 'Speak',
  MUTE_MEMBERS: 'Mute Members',
  DEAFEN_MEMBERS: 'Deafen Members',
  MOVE_MEMBERS: 'Move Members',
  USE_VAD: 'Use Voice Activity',
  CHANGE_NICKNAME: 'Change Nickname',
  MANAGE_NICKNAMES: 'Manage Nicknames',
  MANAGE_ROLES: 'Manage Roles',
  MANAGE_WEBHOOKS: 'Manage Webhooks',
  MANAGE_EMOJIS_AND_STICKERS: 'Manage Emojis and Stickers',
  USE_APPLICATION_COMMANDS: 'Use Application Commands',
  REQUEST_TO_SPEAK: 'Request to Speak',
  MANAGE_EVENTS: 'Manage Events',
  MANAGE_THREADS: 'Manage Threads',
  CREATE_PUBLIC_THREADS: 'Create Public Threads',
  CREATE_PRIVATE_THREADS: 'Create Private Threads',
  USE_EXTERNAL_STICKERS: 'Use External Stickers',
  SEND_MESSAGES_IN_THREADS: 'Send Messages in Threads',
  USE_EMBEDDED_ACTIVITIES: 'Use Embedded Activities',
  MODERATE_MEMBERS: 'Moderate Members',
  VIEW_CREATOR_MONETIZATION_ANALYTICS: 'View Creator Monetization',
  USE_SOUNDBOARD: 'Use Soundboard',
  SEND_VOICE_MESSAGES: 'Send Voice Messages'
};

// Channel types
const CHANNEL_TYPES = {
  GUILD_TEXT: 0,
  DM: 1,
  GUILD_VOICE: 2,
  GROUP_DM: 3,
  GUILD_CATEGORY: 4,
  GUILD_ANNOUNCEMENT: 5,
  ANNOUNCEMENT_THREAD: 10,
  PUBLIC_THREAD: 11,
  PRIVATE_THREAD: 12,
  GUILD_STAGE_VOICE: 13,
  GUILD_DIRECTORY: 14,
  GUILD_FORUM: 15,
  GUILD_MEDIA: 16
};

// Permissions relevant for text channels
const TEXT_CHANNEL_PERMISSIONS = [
  'VIEW_CHANNEL',
  'SEND_MESSAGES',
  'SEND_TTS_MESSAGES',
  'MANAGE_MESSAGES',
  'EMBED_LINKS',
  'ATTACH_FILES',
  'READ_MESSAGE_HISTORY',
  'MENTION_EVERYONE',
  'USE_EXTERNAL_EMOJIS',
  'ADD_REACTIONS',
  'USE_APPLICATION_COMMANDS',
  'MANAGE_THREADS',
  'CREATE_PUBLIC_THREADS',
  'CREATE_PRIVATE_THREADS',
  'USE_EXTERNAL_STICKERS',
  'SEND_MESSAGES_IN_THREADS',
  'SEND_VOICE_MESSAGES'
];

// Permissions relevant for voice channels
const VOICE_CHANNEL_PERMISSIONS = [
  'VIEW_CHANNEL',
  'CONNECT',
  'SPEAK',
  'STREAM',
  'MUTE_MEMBERS',
  'DEAFEN_MEMBERS',
  'MOVE_MEMBERS',
  'USE_VAD',
  'PRIORITY_SPEAKER',
  'USE_SOUNDBOARD',
  'USE_EMBEDDED_ACTIVITIES'
];

// Permissions relevant for categories
const CATEGORY_PERMISSIONS = [
  'VIEW_CHANNEL',
  'MANAGE_CHANNELS',
  'MANAGE_ROLES',
  'CREATE_INSTANT_INVITE'
];

module.exports = {
  DISCORD_PERMISSIONS,
  USER_ROLES,
  PERMISSION_FLAGS,
  PERMISSION_NAMES,
  CHANNEL_TYPES,
  TEXT_CHANNEL_PERMISSIONS,
  VOICE_CHANNEL_PERMISSIONS,
  CATEGORY_PERMISSIONS
};
